blog/urls.py
from django.conf.urls import url
from .views import (
    PostDelete, PostList, PostUpdate,
    PostCreate, post_detail)
    
urlpatterns = [
    url(r'^$',
        PostList.as_view(),
        name='blog_post_list'),
    url(r'^create/$',
        PostCreate.as_view(),
        name='blog_post_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$',
        post_detail,
        name='blog_post_detail'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'delete/$',
        PostDelete.as_view(),
        name='blog_post_delete'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name='blog_post_update'),
]

organizer/urls.py
from django.conf.urls import url

from .views import (
    team_list, tag_list, tag_detail, team_detail,
    TagCreate, TagUpdate, TeamCreate, NewsLinkCreate, NewsLinkDelete,
    TeamUpdate, TeamDelete, TagDelete)

urlpatterns = [
    url(r'^newslink/create/$',
        NewsLinkCreate.as_view(),
        name='organizer_newslink_create'),
    url(r'^newslink/delete/(?P<pk>\d+)/$',
        NewsLinkDelete.as_view(),
        name='organizer_newslink_delete'),
    url(r'^newslink/update/(?P<pk>\d+)/$',
        NewsLinkCreate.as_view(),
        name='organizer_newslink_create'),
    url(r'^team/$',
        team_list,
        name='organizer_team_list'),
    url(r'^team/create/$',
        TeamCreate.as_view(),
        name='organizer_team_create'),
    url(r'^team/(?P<slug>[\w\-]+)/$',
        team_detail,
        name='organizer_team_detail'),
    url(r'^team/(?P<slug>[\w\-]+)/update$',
        TeamUpdate.as_view(),
        name='organizer_team_update'),
    url(r'^team/(?P<slug>[\w\-]+)/delete$',
        TeamDelete.as_view(),
        name='organizer_team_delete'),
    url(r'^tag/$',
        tag_list,
        name='organizer_tag_list'),
     url(r'^tag/create/$',
        TagCreate.as_view(),
        name='organizer_tag_create'),
    url(r'^tag/(?P<slug>[\w\-]+)/$',
        tag_detail,
        name='organizer_tag_detail'),
    url(r'^tag/(?P<slug>[\w\-]+)/update$',
        TagUpdate.as_view(),
        name='organizer_tag_update'),
    url(r'^tag/(?P<slug>[\w\-]+)/delete$',
        TagDelete.as_view(),
        name='organizer_tag_delete'),
    
]

suorganizer/urls.py
from django.urls import path, include
from django.contrib import admin

from blog import urls as blog_urls
from contact import urls as contact_urls
from organizer.urls import (
    newslink as newslink_urls,
    team as team_urls, tag as tag_urls)



from.views import redirect_root

urlpatterns = [
    path('', redirect_root),
    path('admin/', admin.site.urls),
    path('blog/', include(blog_urls)),
    path('contact/', include(contact_urls)),
    path('newslink/', include(contact_urls)),
    path('team/', include(contact_urls)),
    path('tag/', include(contact_urls)),
]

organizer/models.py
from django.urls import reverse
from django.db import models

class Tag(models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(
        max_length=31,
        unique=True,
        help_text='A label for URL config.')
    
    class Meta:
            ordering = ['name']

    def __str__(self):
            return self.name.title()
    
    def get_absolute_url(self):
        return reverse('organizer_tag_detail',
                       kwargs={'slug': self.slug})
    
    def get_update_url(self):
        return reverse('organizer_tag_update',
                       kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('organizer_tag_delete',
                       kwargs={'slug': self.slug})

    

class Team(models.Model):
    name = models.CharField(max_length=31, db_index=True)
    slug = models.SlugField(
        max_length=31,
        unique=True,
        help_text='A label for URL config.'
    )
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField()
    tags = models.ManyToManyField(Tag, blank=True)
    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'

    def __str__(self):
            return self.name.title()
    
    def get_absolute_url(self):
        return reverse('organizer_team_detail',
                       kwargs={'slug': self.slug})
    def get_update_url(self):
        return reverse('organizer_team_update',
                       kwargs={'slug': self.slug})
    def get_delete_url(self):
        return reverse('organizer_team_delete',
                       kwargs={'slug': self.slug})
    
class NewsLink(models.Model):
    title = models.CharField(max_length=31)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    team = models.ForeignKey(Team, on_delete=models.PROTECT)
    slug = models.SlugField(max_length=63)
    
    def __str__(self):
            return "{}:{}".format(
                self.team, self.title)
    
    def get_absolute_url(self):
        return self.team.get-absolute_url()
    
    def get_update_url(self):
        return reverse(
            'organizer_newslink_update',
            kwargs={'pk': self.pk}
        )
    def get_delete_url(self):
        return reverse('organizer_newslink_delete',
                       kwargs={'pk': self.pk})

    class Meta:
        verbose_name = 'news article'
        ordering = ['-pub_date']
        get_latest_by = 'pub_date'
        unique_together= ('slug','team')

organizer/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Tag, NewsLink, Team


class SlugCleanMixin:
    """Mixin class for slug cleaning method."""

    def clean_slug(self):
        new_slug = (
            self.cleaned_data['slug'].lower())
        if new_slug == 'create':
            raise ValidationError(
                'Slug may not be "create".')
        return new_slug

class TagForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'
    
    def clean_name(self):
        return self.cleaned_data['name'].lower()


class NewsLinkForm(forms.ModelForm):
    class Meta:
        model = NewsLink
        fields = '__all__'
    
class TeamForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Team
        fields = '__all__'

organizer/views.py
from django.urls import reverse_lazy
from django.shortcuts import (
    get_object_or_404, redirect, render)
from django.views.generic import View

from .forms import TagForm, TeamForm, NewsLinkForm
from .models import Team, Tag
from .utils import ObjectCreateMixin, ObjectUpdateMixin, ObjectDeleteMixin

class TeamCreate(ObjectCreateMixin, View):
    form_class = TeamForm
    template_name = 'organizer/team_form.html'

class TeamUpdate(ObjectUpdateMixin, View):
    form_class = TeamForm
    model = Team
    template_name = 'organizer/team_form_update.html'


def team_detail(request, slug):
    startup = get_object_or_404(
        Team, slug__iexact=slug)
    return render(
        request,
        'organizer/team_detail.html',
        {'team': team})

class TeamDelete(ObjectDeleteMixin, View):
    model = Team
    success_url = reverse_lazy(
        'organizer_team_list'
    )
    template_name = 'organizer/team_confirm_delete.html'


class NewsLinkCreate(ObjectCreateMixin, View):
    form_class = NewsLinkForm
    template_name = 'organizer/newslink_form.html'

class NewsLinkDelete(View):

    def get(self, request, pk):
        newslink = get_object_or_404(
            NewsLink, pk=pk)
        return render(
            request,
            'organizer/'
            'newslink_confirm_delete.html',
            {'newslink': newslink})

    def post(self, request, pk):
        newslink = get_object_or_404(
            NewsLink, pk=pk)
        team = newslink.team
        newslink.delete()
        return redirect(team)

class NewsLinkUpdate(View):
    form_class = NewsLinkForm
    template_name = 'organizer/newslink_form_update.html'

    def post(self, request, pk):
        newslink = get_object_or_404(
            NewsLink, pk=pk
        )
        bound_form = self.form_class(
            request.POST, instance=newslink
        )
        if bound_form.is_valid():
            new_newslink = bouund_form.save()
            return redirect(new_newslink)
        else:
            context = {
                'form': form,
                'newslink': newslink,
            }
            return render(
                request,
                self.template_name,
                context
            )

def team_list(request):
    return render(
        request,
        'organizer/team_list.html',
        {'team_list': Team.objects.all()})


class TagCreate(ObjectCreateMixin, View):
    form_class = TagForm
    template_name = 'organizer/tag_form.html'

class TagUpdate(ObjectUpdateMixin, View):
    form_class = TagForm
    model = Tag
    template_name = 'organizer/tag_form_update.html'

def tag_detail(request, slug):
    tag = get_object_or_404(
        Tag, slug__iexact=slug)
    return render(
        request,
        'organizer/tag_detail.html',
        {'tag': tag})


def tag_list(request):
    return render(
        request,
        'organizer/tag_list.html',
        {'tag_list': Tag.objects.all()})

class TagDelete(ObjectDeleteMixin, View):
    model = Tag
    success_url = reverse_lazy(
        'organizer_tag_list'
    )
    template_name = 'organizer/tag_confirm_delete.html'

organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

organizer/templates/organizer/newslink_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Link News Article to Startup
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{% url 'organizer_newslink_create' %}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Link Article</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/tag_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Delete Tag
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{{ tag.get_delete_url }}"
          method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete
          tag {{ tag.name }}?
        </p>
        <a href="{{ tag.get_absolute_url }}">
          Cancel</a>
        <button type="submit">Delete Tag</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - {{ tag.name|title }}
{% endblock %}

{% block content %}
<h2>{{ tag.name|title }}</h2>
    {% if tag.team_set.all %}
    <ul>
        <li>
            <a href="{{ tag.get_update_url }}">Edit Tag</a>
        </li>
        <li>
            <a href="{{ tag.get_delete_url }}">Delete Tag</a>
        </li>
    </ul>
    <section>
        <h3>Teams{{tag.team_set.count|pluralize }}</h3>
        <p>
            Tag is associated with
            {{ tag.team_set.count }}
            team{{ tag.startup_set.count|pluralize }}
        </p>
        <ul>
            {% for team in tag.team_set.all %}
                <li><a href="{{ startup.get_absolute_url }}">
                    {{ team.name }}
                </a></li>
            {% endfor %}
        </ul>
    </section>
    {% endif %}
        {% if tag.blog_posts.all %}
        <section>
            <h3>Blog Posts {{ tag.blog_posts.count|pluralize }}</h3>
            <ul>
                {% for post in tag.blog_posts.all %}
                <li><a href="{{ post.get_absolute_url }}">{{ blog.title|title }}</a></li>
            {% endfor %}
            </ul>
        </section>
        {% end if %}
        {% if not tag.startup_set.all and not tag.blog_posts.all %}
            <p>This tag is not related to any content.</p>
        {% endif %}
 {% endblock %}

organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Tag
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{% url 'organizer_tag_create' %}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Create Tag</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/tag_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Update Tag
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{{ tag.get_update_url }}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Update Tag</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Tag List
{% endblock %}

{% block content %}
  <h2>Tag List</h2>
  <div>
    <a href="{% url 'organizer_tag_create' %}">
      Create New Tag</a>
  </div>
  <ul>
    {% for tag in tag_list %}
      <li>
        <a href="{{ tag.get_absolute_url }}">
          {{ tag.name|title }}</a>
      </li>
      <ul>
        <li>
            <a href="{{ tag.get_update_url }}">Edit Tag</a>
        </li>
    </ul>
    {% empty %}
      <li><em>There are currently no Tags available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}

organizer/templates/organizer/team_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - {{ team.name }}
{% endblock %}

{% block content %}
<article>

    <h2>{{ team.name }}</h2>
    <ul>
      <li>
          <a href="{{ team.get_update_url }}">Edit Team</a>
      </li>
  </ul>
    <dl>
      <dt>Date Founded</dt>
        <dd>{{ team.founded_date|date:"F jS, Y" }}</dd>
      <dt>Website</dt>
        <dd>{{ team.website|urlize }}</dd>
      <dt>Contact</dt>
        <dd>{{ team.contact }}</dd>
  
        <dt>Tag{{ team.tags.count|pluralize }}</dt>
          {% for tag in team.tags.all %}
            <dd><a href="{{ tag.get_absolute_url }}">
              {{ tag.name|title }}
            </a></dd>
          {% endfor %}
  
    </dl>
  
    {{ team.description|linebreaks }}
  
        {% if team.newslink_set.all %}
            <section>
              <h3>Recent News</h3>
              <p>
                <a href="{% url 'organizer_newslink_create' %}">
                  Add Article
                </a></p>
              <ul>
                {% for newslink in startup.newslink_set.all %}
                  <li>
                    <a href="{{ newslink.link }}">
                      {{ newslink.title|title }}</a>
                      <ul>
                          <li>
                            <a href="{{ newslink.get_update_url }}">
                              Edit Link</a></li>
                          <li>
                            <a href="{{ newslink.get_delete_url }}">
                              Delete Link</a></li>
                      </ul>
                  </li>
                {% endfor %}
              </ul>
            </section
        {% endif %}
  
        {% if team.blog_posts.all %}
            <section>
              <h3>Blog Post{{ team.blog_posts.all|pluralize }}</h3>
              <ul>
                {% for post in team.blog_posts.all %}
                  <li>
                    <a href="{{ post.get_absolute_url }}">
                      {{ post.title|title }}</a>
                  </li>
                {% endfor %}
              </ul>
            </section>
        {% endif %}
  
  </article>
{% endblock %}

organizer/templates/organizer/team_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Team
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{% url 'organizer_team_create' %}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Create Team</button>
      </form>
    </div>
  </div>
{% endblock %}

organizer/templates/organizer/team_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Teams
{% endblock %}

{% block content %}
  <h2>Team List</h2>
    <div>
      <a href="{% url 'organizer_team_create' %}">
        Create New Team</a>
    </div>
  <ul>
    {% for team in team_list %}
      <li>
        <a href="{{ team.get_absolute_url }}">
          {{ team.name }}</a>
          <ul>
            <li>
                <a href="{{ team.get_update_url }}">
                  Edit Team</a></li>
            <li>
              <a href="{{ team.get_delete_url }}">
                Delete Tag</a></li>
          </ul>
      </li>
    {% empty %}
      <li><em>No Teams Available</em></li>
    {% endfor %}
  </ul>
{% endblock %}